ARG DOCKER_REGISTRY=docker.io
FROM ${DOCKER_REGISTRY}/duckietown/dt-gui-tools:daffy-staging-x-amd64

RUN /usr/bin/python3 -m pip install --upgrade pip


RUN pip3 install -U \
    aido-protocols-daffy \
    duckietown-world-daffy \
    tqdm \
    ipywidgets

RUN apt-get update -y && apt-get install -y  \
    freeglut3-dev \
    python3-pip \
    python3-numpy \
    python3-scipy \
    wget curl vim git \
    && \
    rm -rf /var/lib/apt/lists/*

RUN apt update && apt install unzip

COPY requirements.txt requirements.txt
RUN pip3 install -U -r requirements.txt

RUN pip3 uninstall dataclasses -y
RUN python3 -m pip install pyglet==1.5.15



# note that this CMD normally gets overwritten
CMD ["dt-launcher-jupyter"]


