ARG DOCKER_REGISTRY=docker.io
FROM ${DOCKER_REGISTRY}/duckietown/dt-gui-tools:daffy-staging-x-amd64

RUN /usr/bin/python3 -m pip install --upgrade pip


RUN pip3 install -U \
    aido-protocols-daffy \
    duckietown-world-daffy \
    tqdm \
    ipywidgets

RUN apt update && apt install libglvnd-dev -y

RUN apt update && apt install unzip

COPY requirements.txt requirements.txt
RUN pip3 install -U -r requirements.txt



RUN pip3 uninstall dataclasses -y

RUN python3 -m pip install pyglet==1.5.15

# note that this CMD normally gets overwritten
CMD ["dt-launcher-jupyter"]


